# Generated by Django 5.2.9 on 2025-12-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('tipo_ente', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('ONG', 'ONG')], max_length=10)),
                ('persona_contacto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_bcv', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha_pago', models.DateTimeField()),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_MOVIL', 'Pago Móvil'), ('OTRO', 'Otro')], max_length=15)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('verificado_admin', models.BooleanField(default=False)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='filiacion.representante')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aporte', models.DateField()),
                ('tipo', models.CharField(choices=[('MONETARIO', 'Monetario'), ('INSUMOS', 'Insumos')], max_length=10)),
                ('descripcion', models.TextField()),
                ('valor_estimado_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('patrocinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='finanzas.patrocinante')),
            ],
        ),
    ]
