# Generated by Django 5.2.9 on 2026-04-29 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiacion', '0003_representante_telegram_chat_id_representante_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('tipo_ente', models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado'), ('ONG', 'ONG')], max_length=10)),
                ('persona_contacto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Auto-generado desde mensualidades cubiertas, o texto libre', max_length=200)),
                ('metodo', models.CharField(choices=[('PAGO_MOVIL', 'Pago Móvil'), ('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO_BS', 'Efectivo Bs'), ('EFECTIVO_USD', 'Efectivo USD'), ('OTRO', 'Otro')], max_length=15)),
                ('banco_emisor', models.CharField(blank=True, choices=[('0102', 'Banco de Venezuela'), ('0105', 'Mercantil'), ('0108', 'BBVA Provincial'), ('0114', 'Bancaribe'), ('0134', 'Banesco'), ('0151', 'BFC Banco Fondo Común'), ('0156', '100% Banco'), ('0163', 'Banco del Tesoro'), ('0172', 'Bancamiga'), ('0174', 'Banplus'), ('0175', 'Bicentenario'), ('0191', 'BNC Nacional de Crédito'), ('OTRO', 'Otro')], max_length=4)),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=30)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago', models.DateField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.FileField(upload_to='pagos/%Y/%m/')),
                ('comprobante_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='filiacion.representante')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.IntegerField(help_text='1-12')),
                ('periodo_anio', models.IntegerField(help_text='Ej: 2026')),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Monto base en USD', max_digits=8)),
                ('fecha_vencimiento', models.DateField()),
                ('pagada', models.BooleanField(db_index=True, default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='filiacion.atleta')),
                ('pago', models.ForeignKey(blank=True, help_text='Pago que cubrió esta mensualidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensualidades_cubiertas', to='finanzas.pago')),
            ],
            options={
                'ordering': ['-periodo_anio', '-periodo_mes'],
            },
        ),
        migrations.CreateModel(
            name='PagoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EDITADO', 'Editado'), ('ANULADO', 'Anulado'), ('MENSUALIDADES_VINCULADAS', 'Mensualidades vinculadas')], max_length=30)),
                ('estado_anterior', models.CharField(blank=True, max_length=15)),
                ('estado_nuevo', models.CharField(blank=True, max_length=15)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_audit', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='finanzas.pago')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aporte', models.DateField()),
                ('tipo', models.CharField(choices=[('MONETARIO', 'Monetario'), ('INSUMOS', 'Insumos')], max_length=10)),
                ('descripcion', models.TextField()),
                ('valor_estimado_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('patrocinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='finanzas.patrocinante')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'APROBADO'])), fields=('banco_emisor', 'referencia'), name='uniq_referencia_activa'),
        ),
        migrations.AddIndex(
            model_name='mensualidad',
            index=models.Index(fields=['pagada', 'fecha_vencimiento'], name='finanzas_me_pagada_a0750b_idx'),
        ),
        migrations.AddIndex(
            model_name='mensualidad',
            index=models.Index(fields=['atleta', 'pagada'], name='finanzas_me_atleta__64f81a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mensualidad',
            unique_together={('atleta', 'periodo_mes', 'periodo_anio')},
        ),
        migrations.AddIndex(
            model_name='pagoauditlog',
            index=models.Index(fields=['pago', '-timestamp'], name='finanzas_pa_pago_id_794daf_idx'),
        ),
    ]
