# Generated by Django 5.2.9 on 2026-08-06 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('filiacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('tipo_ente', models.CharField(max_length=20)),
                ('persona_contacto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TasaBCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True)),
                ('tasa', models.DecimalField(decimal_places=4, help_text='Bolívares por USD', max_digits=12)),
                ('fuente', models.CharField(default='dolarapi', help_text='Origen: dolarapi, manual, etc.', max_length=50)),
                ('capturada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa BCV',
                'verbose_name_plural': 'Tasas BCV',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Auto-generado desde mensualidades cubiertas, o texto libre', max_length=200)),
                ('referencia', models.CharField(blank=True, db_index=True, max_length=30)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('monto_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_pago', models.DateField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.FileField(upload_to='pagos/%Y/%m/')),
                ('comprobante_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('banco_emisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.catbanco')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.catestadopago')),
                ('metodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.catmetodopago')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='filiacion.representante')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aporte', models.DateField()),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('valor_estimado_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('patrocinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='finanzas.patrocinante')),
            ],
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_mes', models.IntegerField(help_text='1-12', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('periodo_anio', models.IntegerField(help_text='Ej: 2026')),
                ('monto_usd', models.DecimalField(decimal_places=2, help_text='Monto base en USD', max_digits=8)),
                ('fecha_vencimiento', models.DateField()),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='filiacion.atleta')),
                ('pago', models.ForeignKey(blank=True, help_text='Pago que cubrió esta mensualidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensualidades_cubiertas', to='finanzas.pago')),
            ],
            options={
                'verbose_name': 'Mensualidad',
                'verbose_name_plural': 'Mensualidades',
                'ordering': ['-periodo_anio', '-periodo_mes'],
                'indexes': [models.Index(fields=['atleta'], name='finanzas_me_atleta__bf911c_idx')],
                'unique_together': {('atleta', 'periodo_mes', 'periodo_anio')},
            },
        ),
        migrations.CreateModel(
            name='PagoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_audit', to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='finanzas.pago')),
            ],
            options={
                'verbose_name': 'Log de Auditoría de Pago',
                'verbose_name_plural': 'Logs de Auditoría de Pagos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['pago', '-timestamp'], name='finanzas_pa_pago_id_794daf_idx')],
            },
        ),
    ]
