# Generated by Django 5.2.9 on 2026-08-08 23:44
# Conversión CharField -> FK a catálogos de core con backfill de datos.

import django.db.models.deletion
from django.db import migrations, models


def backfill_fks_catalogo(apps, schema_editor):
    """
    Backfill previo a la conversión CharField -> FK:
    - TasaBCV.fuente_fk: mapea los strings historicos ('dolarapi', 'manual',
      'seed') a registros de CatFuenteTasaBCV.
    - Patrocinante.tipo_ente_fk / Aporte.tipo_fk: mapea valores coincidentes
      y deja NULL los textos libres no catalogados (el campo es null=True).
    """
    TasaBCV = apps.get_model('finanzas', 'TasaBCV')
    Patrocinante = apps.get_model('finanzas', 'Patrocinante')
    Aporte = apps.get_model('finanzas', 'Aporte')
    CatFuenteTasaBCV = apps.get_model('core', 'CatFuenteTasaBCV')
    CatTipoPatrocinante = apps.get_model('core', 'CatTipoPatrocinante')

    fuentes = {f.codigo: f.pk for f in CatFuenteTasaBCV.objects.all()}
    tipos = {t.codigo: t.pk for t in CatTipoPatrocinante.objects.all()}

    for tasa in TasaBCV.objects.exclude(fuente__isnull=True).exclude(fuente=''):
        pk = fuentes.get(str(tasa.fuente).strip().upper())
        if pk is not None:
            tasa.fuente_fk_id = pk
            tasa.save(update_fields=['fuente_fk_id'])

    for pat in Patrocinante.objects.exclude(tipo_ente__isnull=True).exclude(tipo_ente=''):
        pk = tipos.get(str(pat.tipo_ente).strip().upper())
        if pk is not None:
            pat.tipo_ente_fk_id = pk
            pat.save(update_fields=['tipo_ente_fk_id'])

    for apo in Aporte.objects.exclude(tipo__isnull=True).exclude(tipo=''):
        pk = tipos.get(str(apo.tipo).strip().upper())
        if pk is not None:
            apo.tipo_fk_id = pk
            apo.save(update_fields=['tipo_fk_id'])


def revert_backfill_fks_catalogo(apps, schema_editor):
    """Reversión: restaura los códigos textuales desde las FKs conocidas."""
    TasaBCV = apps.get_model('finanzas', 'TasaBCV')
    Patrocinante = apps.get_model('finanzas', 'Patrocinante')
    Aporte = apps.get_model('finanzas', 'Aporte')
    CatFuenteTasaBCV = apps.get_model('core', 'CatFuenteTasaBCV')
    CatTipoPatrocinante = apps.get_model('core', 'CatTipoPatrocinante')

    fuentes = {f.pk: f.codigo for f in CatFuenteTasaBCV.objects.all()}
    tipos = {t.pk: t.codigo for t in CatTipoPatrocinante.objects.all()}

    for tasa in TasaBCV.objects.exclude(fuente_fk_id__isnull=True):
        tasa.fuente = fuentes.get(tasa.fuente_fk_id, '')
        tasa.save(update_fields=['fuente'])

    for pat in Patrocinante.objects.exclude(tipo_ente_fk_id__isnull=True):
        pat.tipo_ente = tipos.get(pat.tipo_ente_fk_id, '')
        pat.save(update_fields=['tipo_ente'])

    for apo in Aporte.objects.exclude(tipo_fk_id__isnull=True):
        apo.tipo = tipos.get(apo.tipo_fk_id, '')
        apo.save(update_fields=['tipo'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_poblar_catalogos_final'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasabcv',
            name='fuente_fk',
            field=models.ForeignKey(blank=True, help_text='Origen de la tasa (DOLARAPI, MANUAL, SEED)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasas_bcv', to='core.catfuentetasabcv'),
        ),
        migrations.AddField(
            model_name='patrocinante',
            name='tipo_ente_fk',
            field=models.ForeignKey(blank=True, help_text='Tipo de ente patrocinante (EMPRESA, PERSONA_NATURAL, INSTITUCION_PUBLICA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrocinantes', to='core.cattipopatrocinante'),
        ),
        migrations.AddField(
            model_name='aporte',
            name='tipo_fk',
            field=models.ForeignKey(blank=True, help_text='Tipo de aporte (EMPRESA, PERSONA_NATURAL, INSTITUCION_PUBLICA)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aportes', to='core.cattipopatrocinante'),
        ),
        migrations.RunPython(backfill_fks_catalogo, revert_backfill_fks_catalogo),
        migrations.RemoveField(
            model_name='tasabcv',
            name='fuente',
        ),
        migrations.RemoveField(
            model_name='patrocinante',
            name='tipo_ente',
        ),
        migrations.RemoveField(
            model_name='aporte',
            name='tipo',
        ),
        migrations.RenameField(
            model_name='tasabcv',
            old_name='fuente_fk',
            new_name='fuente',
        ),
        migrations.RenameField(
            model_name='patrocinante',
            old_name='tipo_ente_fk',
            new_name='tipo_ente',
        ),
        migrations.RenameField(
            model_name='aporte',
            old_name='tipo_fk',
            new_name='tipo',
        ),
    ]
