# Generated by Django 5.2.9 on 2026-04-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaBCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, unique=True)),
                ('tasa', models.DecimalField(decimal_places=4, help_text='Bolívares por USD', max_digits=12)),
                ('fuente', models.CharField(default='dolarapi', help_text='Origen: dolarapi, manual, etc.', max_length=20)),
                ('capturada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tasa BCV',
                'verbose_name_plural': 'Tasas BCV',
                'ordering': ['-fecha'],
            },
        ),
    ]
