# Generated by Django 5.2.9 on 2026-05-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_tasabcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoauditlog',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EDITADO', 'Editado'), ('ANULADO', 'Anulado'), ('MENSUALIDADES_VINCULADAS', 'Mensualidades vinculadas'), ('COMPROBANTE_DESCARGADO', 'Comprobante descargado')], max_length=30),
        ),
    ]
