# Generated by Django 5.2.9 on 2025-12-02 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('GENERAL', 'General'), ('DEPORTIVO', 'Deportivo')], max_length=10)),
                ('usuario_sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinador_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('licencia', models.CharField(choices=[('FVF', 'Licencia FVF'), ('CONMEBOL', 'Licencia CONMEBOL')], max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenadores_a_cargo', to='administracion.coordinador')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('anio_nacimiento_min', models.PositiveIntegerField()),
                ('anio_nacimiento_max', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('MIXTO', 'Mixto')], max_length=10)),
                ('coordinador_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_supervisadas', to='administracion.coordinador')),
                ('delegado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_delegada', to='administracion.delegado')),
                ('entrenadores_asignados', models.ManyToManyField(blank=True, related_name='categorias_asignadas', to='administracion.entrenador')),
            ],
        ),
    ]
