# Generated by Django 5.2.9 on 2026-08-06 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='core.catcargo')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal', to='core.catlicencia')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_personal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('anio_nacimiento_min', models.IntegerField()),
                ('anio_nacimiento_max', models.IntegerField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='core.catgenero')),
                ('coordinador_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_coordinadas', to='administracion.personal')),
                ('delegado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias_delegadas', to='administracion.personal')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='CategoriaEntrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_entrenadores', to='administracion.categoria')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_asignadas', to='administracion.personal')),
            ],
            options={
                'verbose_name': 'Asignación de Entrenador a Categoría',
                'verbose_name_plural': 'Asignaciones de Entrenadores a Categorías',
                'unique_together': {('categoria', 'personal')},
            },
        ),
    ]
