# Generated by Django 5.2.9 on 2026-08-15 21:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cedula_identidad',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[core.validators.validar_cedula_venezolana]),
        ),
    ]
