# Generated by Django 5.2.9 on 2026-07-31 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
        ('core', '0002_poblar_catalogos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_identidad', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personal2', to='core.catcargo')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal2', to='core.catlicencia')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_personal2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal (v2)',
                'verbose_name_plural': 'Personal (v2)',
            },
        ),
        migrations.CreateModel(
            name='Categoria2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('anio_nacimiento_min', models.IntegerField()),
                ('anio_nacimiento_max', models.IntegerField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias2', to='core.catgenero')),
                ('coordinador_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_coordinadas', to='administracion.personal2')),
                ('delegado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_delegadas2', to='administracion.personal2')),
            ],
            options={
                'verbose_name': 'Categoría (v2)',
                'verbose_name_plural': 'Categorías (v2)',
            },
        ),
        migrations.CreateModel(
            name='CategoriaEntrenadores2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_entrenadores2', to='administracion.categoria2')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_asignadas2', to='administracion.personal2')),
            ],
            options={
                'verbose_name': 'Asignación Entrenador a Categoría (v2)',
                'verbose_name_plural': 'Asignaciones Entrenadores a Categorías (v2)',
                'unique_together': {('categoria', 'personal')},
            },
        ),
    ]
