# Generated by Django 5.2.9
# Data Migration - Fase 2: Migrar datos de Entrenador (viejo) a Personal2 (nuevo)
# Lógica: get_or_create basado en cédula para evitar duplicados.

from django.db import migrations


def migrar_entrenadores_a_personal2(apps, schema_editor):
    """
    Mueve los datos del modelo legado 'Entrenador' (si existe) al nuevo
    modelo 'Personal2' que referencia los catálogos centralizados de `core`.
    """
    # --- Intentamos obtener el modelo legado ---
    try:
        Entrenador = apps.get_model('administracion', 'Entrenador')
    except LookupError:
        # El modelo 'Entrenador' no existe en este proyecto.
        # Esto es un escenario esperado según el PRD. No hacemos nada.
        return

    Personal2 = apps.get_model('administracion', 'Personal2')
    CatCargo = apps.get_model('core', 'CatCargo')

    # Nos aseguramos de que el cargo "Entrenador" exista en el catálogo de core
    cargo_entrenador, _ = CatCargo.objects.get_or_create(
        nombre='Entrenador',
        defaults={'descripcion': 'Entrenador de categoría deportiva'}
    )

    # Iteramos sobre todos los entrenadores del modelo viejo
    for entrenador in Entrenador.objects.all():
        # Mapeamos los campos del modelo viejo al nuevo.
        # Usamos get_or_create con la cédula como clave única para idempotencia.
        Personal2.objects.get_or_create(
            cedula_identidad=entrenador.cedula_identidad,
            defaults={
                'cargo': cargo_entrenador,
                'licencia': None,
                'nombres': getattr(entrenador, 'nombres', getattr(entrenador, 'nombre', 'N/A')),
                'apellidos': getattr(entrenador, 'apellidos', 'N/A'),
                'telefono': getattr(entrenador, 'telefono', ''),
                'activo': getattr(entrenador, 'activo', True),
                'usuario': None,
            }
        )


def revertir_migracion(apps, schema_editor):
    """
    Función de reversión: limpia los registros en Personal2
    que tienen como cargo 'Entrenador', asumiendo que vinieron de aquí.
    """
    Personal2 = apps.get_model('administracion', 'Personal2')
    CatCargo = apps.get_model('core', 'CatCargo')

    try:
        cargo_entrenador = CatCargo.objects.get(nombre='Entrenador')
        Personal2.objects.filter(cargo=cargo_entrenador).delete()
    except CatCargo.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_personal2_categoria2_categoriaentrenadores2'),
        ('core', '0002_poblar_catalogos'),
    ]

    operations = [
        migrations.RunPython(migrar_entrenadores_a_personal2, revertir_migracion),
    ]
