services:
  - type: web
    name: ingeniumcode-fdm
    runtime: docker
    plan: free
    region: oregon
    branch: deploy-render-weasyprint
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ingeniumcode-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_WEBHOOK_SECRET
        sync: false

databases:
  - name: ingeniumcode-db
    databaseName: ingeniumcode_fdm
    user: ingeniumcode_user
    plan: free
    region: oregon
