# Generated by Django 5.2.9 on 2026-08-06 18:25
# Data Migration - Poblar catálogos base (ERD V3.1 / 3NF pura)
# Lógica recuperada de la antigua core/migrations/0002_poblar_catalogos.py
# durante el reset de migraciones (limpieza de deuda técnica legacy).

from django.db import migrations


def poblar_catalogos(apps, schema_editor):
    # Obtención de los modelos a través del registro histórico de Django
    CatBanco = apps.get_model('core', 'CatBanco')
    CatEstadoPago = apps.get_model('core', 'CatEstadoPago')
    CatMetodoPago = apps.get_model('core', 'CatMetodoPago')
    CatGenero = apps.get_model('core', 'CatGenero')
    CatTipoPartido = apps.get_model('core', 'CatTipoPartido')
    CatCondicionPartido = apps.get_model('core', 'CatCondicionPartido')

    # --- CatBanco (Bancos venezolanos - código SUDEBAN) ---
    bancos = [
        {'codigo_sudeban': '0102', 'nombre': 'Banco de Venezuela', 'activo': True},
        {'codigo_sudeban': '0134', 'nombre': 'Banesco',            'activo': True},
        {'codigo_sudeban': '0105', 'nombre': 'Mercantil',          'activo': True},
        {'codigo_sudeban': '0108', 'nombre': 'Provincial',         'activo': True},
    ]
    for b in bancos:
        CatBanco.objects.get_or_create(codigo_sudeban=b['codigo_sudeban'], defaults=b)

    # --- CatEstadoPago ---
    estados_pago = [
        {'codigo': 'PENDIENTE',  'descripcion': 'Transacción por verificar'},
        {'codigo': 'APROBADO',   'descripcion': 'Transacción validada'},
        {'codigo': 'RECHAZADO',  'descripcion': 'Transacción declinada'},
    ]
    for ep in estados_pago:
        CatEstadoPago.objects.get_or_create(codigo=ep['codigo'], defaults=ep)

    # --- CatMetodoPago (códigos unificados con el seed y los tests) ---
    metodos_pago = [
        {'codigo': 'PAGO_MOVIL',    'nombre': 'Pago Móvil'},
        {'codigo': 'TRANSFERENCIA', 'nombre': 'Transferencia'},
        {'codigo': 'EFECTIVO_BS',   'nombre': 'Efectivo Bs'},
        {'codigo': 'EFECTIVO_USD',  'nombre': 'Efectivo USD'},
    ]
    for mp in metodos_pago:
        CatMetodoPago.objects.get_or_create(codigo=mp['codigo'], defaults=mp)

    # --- CatGenero (nombres alineados con el seed y los tests) ---
    generos = ['Masculino', 'Femenino', 'Mixto']
    for g in generos:
        CatGenero.objects.get_or_create(nombre=g)

    # --- CatTipoPartido (códigos alineados con el seed y los tests) ---
    tipos_partido = [
        {'codigo': 'AMISTOSO', 'nombre': 'Amistoso'},
        {'codigo': 'OFICIAL',  'nombre': 'Oficial'},
        {'codigo': 'TORNEO',   'nombre': 'Torneo'},
    ]
    for tp in tipos_partido:
        CatTipoPartido.objects.get_or_create(codigo=tp['codigo'], defaults=tp)

    # --- CatCondicionPartido (códigos alineados con el seed y los tests) ---
    condiciones = [
        {'codigo': 'CASA',      'nombre': 'Casa'},
        {'codigo': 'VISITANTE', 'nombre': 'Visitante'},
        {'codigo': 'NEUTRAL',   'nombre': 'Neutral'},
    ]
    for c in condiciones:
        CatCondicionPartido.objects.get_or_create(codigo=c['codigo'], defaults=c)


def revertir_catalogos(apps, schema_editor):
    """
    Función de reversión: elimina los registros insertados por esta migración.
    Solo borra por los valores de referencia exactos para no tocar datos de usuario.
    """
    CatBanco = apps.get_model('core', 'CatBanco')
    CatEstadoPago = apps.get_model('core', 'CatEstadoPago')
    CatMetodoPago = apps.get_model('core', 'CatMetodoPago')
    CatGenero = apps.get_model('core', 'CatGenero')
    CatTipoPartido = apps.get_model('core', 'CatTipoPartido')
    CatCondicionPartido = apps.get_model('core', 'CatCondicionPartido')

    CatBanco.objects.filter(codigo_sudeban__in=['0102', '0134', '0105', '0108']).delete()
    CatEstadoPago.objects.filter(codigo__in=['PENDIENTE', 'APROBADO', 'RECHAZADO']).delete()
    CatMetodoPago.objects.filter(codigo__in=['PAGO_MOVIL', 'TRANSFERENCIA', 'EFECTIVO_BS', 'EFECTIVO_USD']).delete()
    CatGenero.objects.filter(nombre__in=['Masculino', 'Femenino', 'Mixto']).delete()
    CatTipoPartido.objects.filter(codigo__in=['AMISTOSO', 'OFICIAL', 'TORNEO']).delete()
    CatCondicionPartido.objects.filter(codigo__in=['CASA', 'VISITANTE', 'NEUTRAL']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(poblar_catalogos, revertir_catalogos),
    ]
