# Generated by Django 5.2.9 on 2026-07-31 18:03
# Data Migration - Fase 1: Poblar catálogos base (ERD V2.2)

from django.db import migrations


def poblar_catalogos(apps, schema_editor):
    # Obtención de los modelos a través del registro histórico de Django
    CatBanco = apps.get_model('core', 'CatBanco')
    CatEstadoPago = apps.get_model('core', 'CatEstadoPago')
    CatMetodoPago = apps.get_model('core', 'CatMetodoPago')
    CatGenero = apps.get_model('core', 'CatGenero')
    CatTipoPartido = apps.get_model('core', 'CatTipoPartido')
    CatCondicionPartido = apps.get_model('core', 'CatCondicionPartido')

    # --- CatBanco (Bancos venezolanos - código SUDEBAN) ---
    bancos = [
        {'codigo_sudeban': '0102', 'nombre': 'Banco de Venezuela', 'activo': True},
        {'codigo_sudeban': '0134', 'nombre': 'Banesco',            'activo': True},
        {'codigo_sudeban': '0105', 'nombre': 'Mercantil',          'activo': True},
        {'codigo_sudeban': '0108', 'nombre': 'Provincial',         'activo': True},
    ]
    for b in bancos:
        CatBanco.objects.get_or_create(codigo_sudeban=b['codigo_sudeban'], defaults=b)

    # --- CatEstadoPago ---
    estados_pago = [
        {'codigo': 'PENDIENTE',  'descripcion': 'Transacción por verificar'},
        {'codigo': 'APROBADO',   'descripcion': 'Transacción validada'},
        {'codigo': 'RECHAZADO',  'descripcion': 'Transacción declinada'},
    ]
    for ep in estados_pago:
        CatEstadoPago.objects.get_or_create(codigo=ep['codigo'], defaults=ep)

    # --- CatMetodoPago ---
    metodos_pago = [
        {'codigo': 'PM', 'nombre': 'Pago Móvil'},
        {'codigo': 'TR', 'nombre': 'Transferencia'},
        {'codigo': 'EF', 'nombre': 'Efectivo USD'},
    ]
    for mp in metodos_pago:
        CatMetodoPago.objects.get_or_create(codigo=mp['codigo'], defaults=mp)

    # --- CatGenero ---
    generos = ['MASCULINO', 'FEMENINO']
    for g in generos:
        CatGenero.objects.get_or_create(nombre=g)

    # --- CatTipoPartido ---
    tipos_partido = [
        {'codigo': 'AM', 'nombre': 'AMISTOSO'},
        {'codigo': 'OF', 'nombre': 'OFICIAL'},
        {'codigo': 'TO', 'nombre': 'TORNEO'},
    ]
    for tp in tipos_partido:
        CatTipoPartido.objects.get_or_create(codigo=tp['codigo'], defaults=tp)

    # --- CatCondicionPartido ---
    condiciones = [
        {'codigo': 'LO', 'nombre': 'LOCAL'},
        {'codigo': 'VI', 'nombre': 'VISITANTE'},
        {'codigo': 'NE', 'nombre': 'NEUTRAL'},
    ]
    for c in condiciones:
        CatCondicionPartido.objects.get_or_create(codigo=c['codigo'], defaults=c)


def revertir_catalogos(apps, schema_editor):
    """
    Función de reversión: elimina los registros insertados por esta migración.
    Solo borra por los valores de referencia exactos para no tocar datos de usuario.
    """
    CatBanco = apps.get_model('core', 'CatBanco')
    CatEstadoPago = apps.get_model('core', 'CatEstadoPago')
    CatMetodoPago = apps.get_model('core', 'CatMetodoPago')
    CatGenero = apps.get_model('core', 'CatGenero')
    CatTipoPartido = apps.get_model('core', 'CatTipoPartido')
    CatCondicionPartido = apps.get_model('core', 'CatCondicionPartido')

    CatBanco.objects.filter(codigo_sudeban__in=['0102', '0134', '0105', '0108']).delete()
    CatEstadoPago.objects.filter(codigo__in=['PENDIENTE', 'APROBADO', 'RECHAZADO']).delete()
    CatMetodoPago.objects.filter(codigo__in=['PM', 'TR', 'EF']).delete()
    CatGenero.objects.filter(nombre__in=['MASCULINO', 'FEMENINO']).delete()
    CatTipoPartido.objects.filter(codigo__in=['AM', 'OF', 'TO']).delete()
    CatCondicionPartido.objects.filter(codigo__in=['LO', 'VI', 'NE']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(poblar_catalogos, revertir_catalogos),
    ]
