# Generated by Django 5.2.9 on 2026-08-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260806_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEstadoPartido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de Partido',
                'verbose_name_plural': 'Estados de Partido',
            },
        ),
        migrations.CreateModel(
            name='CatFuenteTasaBCV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fuente de Tasa BCV',
                'verbose_name_plural': 'Fuentes de Tasa BCV',
            },
        ),
        migrations.CreateModel(
            name='CatTipoPatrocinante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Patrocinante',
                'verbose_name_plural': 'Tipos de Patrocinante',
            },
        ),
    ]
