# Generated by Django 5.2.9 on 2026-08-08 23:45
# Data Migration - Poblar catálogos finales del Sprint (ERD V3.1 / 3NF pura):
# CatEstadoPartido, CatTipoPatrocinante y CatFuenteTasaBCV.

from django.db import migrations


def poblar_catalogos_final(apps, schema_editor):
    CatEstadoPartido = apps.get_model('core', 'CatEstadoPartido')
    CatTipoPatrocinante = apps.get_model('core', 'CatTipoPatrocinante')
    CatFuenteTasaBCV = apps.get_model('core', 'CatFuenteTasaBCV')

    # --- CatEstadoPartido (workflow deportivo) ---
    estados_partido = [
        {'codigo': 'PROGRAMADO', 'nombre': 'Programado'},
        {'codigo': 'EN_JUEGO', 'nombre': 'En Juego'},
        {'codigo': 'FINALIZADO', 'nombre': 'Finalizado'},
        {'codigo': 'SUSPENDIDO', 'nombre': 'Suspendido'},
        {'codigo': 'CANCELADO', 'nombre': 'Cancelado'},
    ]
    for ep in estados_partido:
        CatEstadoPartido.objects.get_or_create(codigo=ep['codigo'], defaults=ep)

    # --- CatTipoPatrocinante ---
    tipos_patrocinante = [
        {'codigo': 'EMPRESA', 'nombre': 'Empresa'},
        {'codigo': 'PERSONA_NATURAL', 'nombre': 'Persona Natural'},
        {'codigo': 'INSTITUCION_PUBLICA', 'nombre': 'Institución Pública'},
    ]
    for tp in tipos_patrocinante:
        CatTipoPatrocinante.objects.get_or_create(codigo=tp['codigo'], defaults=tp)

    # --- CatFuenteTasaBCV ---
    fuentes_tasa = [
        {'codigo': 'DOLARAPI', 'nombre': 'DolarAPI'},
        {'codigo': 'MANUAL', 'nombre': 'Manual'},
        {'codigo': 'SEED', 'nombre': 'Seed'},
    ]
    for ft in fuentes_tasa:
        CatFuenteTasaBCV.objects.get_or_create(codigo=ft['codigo'], defaults=ft)


def revertir_catalogos_final(apps, schema_editor):
    """Reversión: elimina únicamente los registros sembrados por esta migración."""
    CatEstadoPartido = apps.get_model('core', 'CatEstadoPartido')
    CatTipoPatrocinante = apps.get_model('core', 'CatTipoPatrocinante')
    CatFuenteTasaBCV = apps.get_model('core', 'CatFuenteTasaBCV')

    CatEstadoPartido.objects.filter(
        codigo__in=['PROGRAMADO', 'EN_JUEGO', 'FINALIZADO', 'SUSPENDIDO', 'CANCELADO']
    ).delete()
    CatTipoPatrocinante.objects.filter(
        codigo__in=['EMPRESA', 'PERSONA_NATURAL', 'INSTITUCION_PUBLICA']
    ).delete()
    CatFuenteTasaBCV.objects.filter(
        codigo__in=['DOLARAPI', 'MANUAL', 'SEED']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_catestadopartido_catfuentetasabcv_and_more'),
    ]

    operations = [
        migrations.RunPython(poblar_catalogos_final, revertir_catalogos_final),
    ]
