# Generated by Django 5.2.9 on 2026-08-06 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(db_index=True, max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('direccion_habitacion', models.TextField()),
                ('telegram_chat_id', models.CharField(blank=True, help_text='ID de chat de Telegram para notificaciones', max_length=20)),
                ('usuario', models.OneToOneField(blank=True, help_text='Cuenta de usuario asociada al representante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acta_nacimiento', models.CharField(blank=True, help_text='Partida/Acta de Nacimiento LOPNNA', max_length=50)),
                ('cedula_identidad', models.CharField(blank=True, db_index=True, help_text='Obligatorio SAIME >= 9 años', max_length=15, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='atletas/fotos/')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_mts', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('es_condicion_especial', models.BooleanField(default=False)),
                ('observacion_medica', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('becado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atletas', to='administracion.categoria')),
                ('lateralidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atletas', to='core.catlateralidad')),
                ('posicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atletas', to='core.catposicion')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='filiacion.representante')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
            },
        ),
    ]
