# Generated by Django 5.2.9 on 2025-12-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono_principal', models.CharField(max_length=20)),
                ('direccion_habitacion', models.TextField()),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_escolar', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_perfil_url', models.URLField(blank=True, max_length=255, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura_mts', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lateralidad', models.CharField(choices=[('DERECHO', 'Derecho'), ('IZQUIERDO', 'Izquierdo'), ('AMBIDIESTRO', 'Ambidiestro')], max_length=11)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('activo', models.BooleanField(default=True)),
                ('becado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas', to='administracion.categoria')),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='filiacion.representante')),
            ],
        ),
    ]
