# Generated by Django 5.2.9 on 2025-12-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='foto_perfil_url',
        ),
        migrations.AddField(
            model_name='atleta',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='atletas/fotos/'),
        ),
    ]
