# Generated by Django 5.2.9 on 2026-08-15 21:37

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='cedula_identidad',
            field=models.CharField(blank=True, db_index=True, help_text='Obligatorio SAIME >= 9 años', max_length=15, null=True, unique=True, validators=[core.validators.validar_cedula_venezolana]),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cedula_identidad',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[core.validators.validar_cedula_venezolana]),
        ),
    ]
