# Generated by Django 5.2.9 on 2026-04-29 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiacion', '0002_remove_atleta_foto_perfil_url_atleta_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='representante',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID de chat de Telegram para notificaciones', max_length=20),
        ),
        migrations.AddField(
            model_name='representante',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Cuenta de usuario asociada al representante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representante', to=settings.AUTH_USER_MODEL),
        ),
    ]
