# Generated by Django 5.2.9 on 2025-12-02 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('rubro', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('descripcion_insumo', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_total_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='logistica.proveedor')),
            ],
        ),
    ]
