# Generated by Django 5.2.9 on 2026-07-31 07:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('filiacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAT_CondicionPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catálogo - Condición de Partido',
                'verbose_name_plural': 'Catálogos - Condiciones de Partidos',
            },
        ),
        migrations.CreateModel(
            name='CAT_TipoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Catálogo - Tipo de Partido',
                'verbose_name_plural': 'Catálogos - Tipos de Partidos',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPsicosocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('compromiso', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('puntualidad', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('companerismo', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('respeto', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('manejo_frustracion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('observaciones_conductuales', models.TextField(blank=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_psicosociales', to='filiacion.atleta')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_psicosociales_realizadas', to='administracion.personal')),
            ],
            options={
                'verbose_name': 'Evaluación Psicosocial',
                'verbose_name_plural': 'Evaluaciones Psicosociales',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('control_balon', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('conduccion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pase_corto', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tiro', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('inteligencia_tactica', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('observaciones', models.TextField(blank=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_tecnicas', to='filiacion.atleta')),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_tecnicas_realizadas', to='administracion.personal')),
            ],
            options={
                'verbose_name': 'Evaluación Técnica',
                'verbose_name_plural': 'Evaluaciones Técnicas',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('equipo_rival', models.CharField(max_length=100)),
                ('goles_favor_escuela', models.PositiveIntegerField(default=0)),
                ('goles_contra_rival', models.PositiveIntegerField(default=0)),
                ('procesado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='administracion.categoria')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='deportivo.cat_condicionpartido')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='deportivo.cat_tipopartido')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_titular', models.BooleanField(default=False)),
                ('minutos_jugados', models.PositiveIntegerField(default=0)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveIntegerField(default=0)),
                ('calificacion_dt', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='filiacion.atleta')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='deportivo.partido')),
            ],
            options={
                'verbose_name': 'Estadística',
                'verbose_name_plural': 'Estadísticas',
                'unique_together': {('atleta', 'partido')},
            },
        ),
    ]
