# Generated by Django 5.2.9 on 2025-12-02 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('filiacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('equipo_rival', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('AMISTOSO', 'Amistoso'), ('OFICIAL', 'Oficial')], max_length=10)),
                ('condicion', models.CharField(choices=[('CASA', 'Casa'), ('VISITANTE', 'Visitante')], max_length=10)),
                ('goles_favor_escuela', models.PositiveIntegerField(default=0)),
                ('goles_contra_rival', models.PositiveIntegerField(default=0)),
                ('resultado', models.CharField(blank=True, choices=[('VICTORIA', 'Victoria'), ('EMPATE', 'Empate'), ('DERROTA', 'Derrota')], max_length=10)),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eval_Psicosocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('compromiso', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('puntualidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('companerismo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('respeto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('manejo_frustracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('observaciones_conductuales', models.TextField(blank=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_psicosociales', to='filiacion.atleta')),
                ('coordinador_evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_psicosociales_realizadas', to='administracion.coordinador')),
            ],
        ),
        migrations.CreateModel(
            name='Eval_Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('velocidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('resistencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('control_balon', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pase', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('tiro', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('inteligencia_tactica', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('observaciones', models.TextField(blank=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_tecnicas', to='filiacion.atleta')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='administracion.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_titular', models.BooleanField(default=False)),
                ('minutos_jugados', models.PositiveIntegerField(default=0)),
                ('goles', models.PositiveIntegerField(default=0)),
                ('asistencias', models.PositiveIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveIntegerField(default=0)),
                ('tarjetas_rojas', models.PositiveIntegerField(default=0)),
                ('calificacion_dt', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='filiacion.atleta')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='deportivo.partido')),
            ],
            options={
                'unique_together': {('atleta', 'partido')},
            },
        ),
    ]
