# Generated by Django 5.2.9 on 2026-08-08 23:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_estado_partido(apps, schema_editor):
    """
    Backfill: asigna estado a los partidos existentes antes de eliminar el
    booleano `procesado`. Los partidos con resultado o estadísticas quedan
    FINALIZADO; el resto queda PROGRAMADO.
    """
    Partido = apps.get_model('deportivo', 'Partido')
    Estadistica = apps.get_model('deportivo', 'Estadistica')
    CatEstadoPartido = apps.get_model('core', 'CatEstadoPartido')

    finalizado, _ = CatEstadoPartido.objects.get_or_create(
        codigo='FINALIZADO', defaults={'nombre': 'Finalizado'}
    )
    programado, _ = CatEstadoPartido.objects.get_or_create(
        codigo='PROGRAMADO', defaults={'nombre': 'Programado'}
    )

    con_resultado = Partido.objects.filter(
        models.Q(goles_favor_escuela__gt=0) | models.Q(goles_contra_rival__gt=0)
    )
    con_estadisticas = Partido.objects.filter(
        pk__in=Estadistica.objects.values_list('partido_id', flat=True)
    )
    finalizados_ids = set(con_resultado.values_list('pk', flat=True)) | set(
        con_estadisticas.values_list('pk', flat=True)
    )
    if finalizados_ids:
        Partido.objects.filter(pk__in=finalizados_ids).update(estado=finalizado)
    if finalizados_ids:
        Partido.objects.exclude(pk__in=finalizados_ids).update(estado=programado)
    else:
        Partido.objects.update(estado=programado)


def revert_backfill_estado_partido(apps, schema_editor):
    """Reversión: limpia el estado (la columna se elimina con la reversión)."""
    Partido = apps.get_model('deportivo', 'Partido')
    Partido.objects.update(estado=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_poblar_catalogos_final'),
        ('deportivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='procesado',
        ),
        migrations.AddField(
            model_name='partido',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado del partido (PROGRAMADO, EN_JUEGO, FINALIZADO, SUSPENDIDO, CANCELADO)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='core.catestadopartido'),
        ),
        migrations.RunPython(backfill_estado_partido, revert_backfill_estado_partido),
    ]
