# Generated by Django 5.2.9 on 2026-02-06 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20251205_1757'),
        ('deportivo', '0002_remove_eval_tecnica_atleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='administracion.categoria'),
        ),
    ]
